apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-reader-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::617998378772:role/s3-list-buckets-role
    
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::617998378772:role/cluster-autoscaler-role